name: build

on:
  push:
  pull_request:
  workflow_run:
    # Use a workflow as a trigger of scheduled builds. Forked repositories can disable scheduled builds by disabling
    # "scheduled" workflow, while maintaining ability to perform local CI builds.
    workflows:
      - scheduled
    branches:
      - master
      - docking
    types:
      - requested

jobs:
  Emscripten:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        wget -q https://github.com/emscripten-core/emsdk/archive/master.tar.gz
        tar -xvf master.tar.gz
        emsdk-master/emsdk update
        emsdk-master/emsdk install latest
        emsdk-master/emsdk activate latest

    - name: Build example_sdl2_opengl3 with Emscripten
      run: |
        pushd emsdk-master
        source ./emsdk_env.sh
        popd
        make -C examples/example_sdl2_opengl3 -f Makefile.emscripten
        

    - name: Build example_emscripten_wgpu
      run: |
        pushd emsdk-master
        source ./emsdk_env.sh
        popd
        make -C examples/example_emscripten_wgpu
    
        
      
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: tes
        path: home/runner/work/imgui/imgui/examples/example_emscripten_wgpu
      

